/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario.operacao;

import fachada.ServidorClinica;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.entidade.Funcionario;
import negocio.entidade.Medico;
import negocio.entidade.Paciente;
import negocio.excecao.funcionario.FuncionarioInexistenteException;
import negocio.excecao.medico.MedicoInexistenteException;
import negocio.excecao.paciente.PacienteInexistenteException;

/**
 *
 * @author Usuário
 */
public class JanelaExibeObjeto extends javax.swing.JDialog {

    Object elemento;
    ServidorClinica fachada;
    
    /**
     * Creates new form JanelaExibeObjeto
     */
    public JanelaExibeObjeto(Object elemento, ServidorClinica fachada){
        this.elemento = elemento;
        this.fachada = fachada;
        initComponents();
        setModal(true);
        if (elemento instanceof Funcionario){
            Funcionario temp = (Funcionario) elemento;
            nomeFunc.setText(temp.getNome());
            cpfFunc.setText(temp.getCpf());
            loginFunc.setText(temp.getLogin());
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "panelFuncionario");
        } else if (elemento instanceof Medico){
            Medico temp = (Medico) elemento;
            nomeMedico.setText(temp.getNome());
            cpfMedico.setText(temp.getCpf());
            crmMedico.setText(temp.getCrm());
            loginMedico.setText(temp.getLogin());
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "panelMedico");
        } else if (elemento instanceof Paciente){
            Paciente temp = (Paciente) elemento;
            nomePaciente.setText(temp.getNome());
            cpfResponsavel.setText(temp.getCpf());
            nomeResponsavel.setText(temp.getNomeResponsavel());
            numeroTelefone.setText(temp.getNumeroContato());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String data = sdf.format(temp.getDataNascimento());
            dataNascimento.setText(data);
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "panelPaciente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Informações = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        panelFuncionario = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeFunc = new javax.swing.JLabel();
        cpfFunc = new javax.swing.JLabel();
        loginFunc = new javax.swing.JLabel();
        panelMedico = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeMedico = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cpfMedico = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginMedico = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        crmMedico = new javax.swing.JLabel();
        panelPaciente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nomePaciente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nomeResponsavel = new javax.swing.JLabel();
        cpfResponsavel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        numeroTelefone = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dataNascimento = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Informações.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Informações.setText("Informações");

        mainPanel.setLayout(new java.awt.CardLayout());

        panelFuncionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel.setText("Nome:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CPF:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Login:");

        nomeFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeFunc.setText("Nome do Funcionario");

        cpfFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfFunc.setText("CPF do Funcionario");

        loginFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginFunc.setText("Login do Funcionario");

        javax.swing.GroupLayout panelFuncionarioLayout = new javax.swing.GroupLayout(panelFuncionario);
        panelFuncionario.setLayout(panelFuncionarioLayout);
        panelFuncionarioLayout.setHorizontalGroup(
            panelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeFunc))
                    .addGroup(panelFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpfFunc))
                    .addGroup(panelFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginFunc)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        panelFuncionarioLayout.setVerticalGroup(
            panelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(nomeFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cpfFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loginFunc))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        mainPanel.add(panelFuncionario, "panelFuncionario");

        panelMedico.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");

        nomeMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeMedico.setText("Nome do Funcionario");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CPF:");

        cpfMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfMedico.setText("CPF do Funcionario");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Login:");

        loginMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginMedico.setText("Login do Funcionario");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CRM:");

        crmMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crmMedico.setText("Nome do Funcionario");

        javax.swing.GroupLayout panelMedicoLayout = new javax.swing.GroupLayout(panelMedico);
        panelMedico.setLayout(panelMedicoLayout);
        panelMedicoLayout.setHorizontalGroup(
            panelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMedicoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeMedico))
                    .addGroup(panelMedicoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpfMedico)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crmMedico))
                    .addGroup(panelMedicoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginMedico)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        panelMedicoLayout.setVerticalGroup(
            panelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeMedico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(crmMedico))
                    .addGroup(panelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cpfMedico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loginMedico))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        mainPanel.add(panelMedico, "panelMedico");

        panelPaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nome:");

        nomePaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomePaciente.setText("nomepaciente");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nome Responsável:");

        nomeResponsavel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeResponsavel.setText("nomeResponsavel");

        cpfResponsavel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfResponsavel.setText("cpfResponsavel");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CPF do responsável:");

        numeroTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroTelefone.setText("numeroTelefone");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Número para contato:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Data de nascimento:");

        dataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dataNascimento.setText("dataNascimento");

        javax.swing.GroupLayout panelPacienteLayout = new javax.swing.GroupLayout(panelPaciente);
        panelPaciente.setLayout(panelPacienteLayout);
        panelPacienteLayout.setHorizontalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPacienteLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataNascimento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelPacienteLayout.createSequentialGroup()
                        .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPacienteLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeResponsavel))
                            .addGroup(panelPacienteLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPacienteLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(16, 16, 16)
                                .addComponent(numeroTelefone))
                            .addGroup(panelPacienteLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpfResponsavel)))
                        .addContainerGap(150, Short.MAX_VALUE))))
        );
        panelPacienteLayout.setVerticalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nomePaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dataNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeResponsavel)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cpfResponsavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(numeroTelefone))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mainPanel.add(panelPaciente, "panelPaciente");

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Informações)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoVoltar))
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Informações)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int resul = JOptionPane.showConfirmDialog(null, "Deseja remover essa pessoa do sistema?","Confirmação",JOptionPane.YES_OPTION);
        if(resul == 0){
            if (elemento instanceof Funcionario){
                try {
                    fachada.removerFuncionario(Integer.toString(((Funcionario)elemento).getId()));
                } catch (FuncionarioInexistenteException ex) {
                    // Já foi verificada essa exceção
                }
            } else if (elemento instanceof Medico){
                try {
                    fachada.removerMedico(((Medico)elemento).getCrm());
                } catch (MedicoInexistenteException ex) {
                    // Exceção já verificada
                }
            } else if (elemento instanceof Paciente){
                try {
                    fachada.removerPaciente(((Paciente)elemento).getCpf());
                } catch (PacienteInexistenteException ex) {
                    // Exceção já verificada
                }
            }
            dispose();
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Informações;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel cpfFunc;
    private javax.swing.JLabel cpfMedico;
    private javax.swing.JLabel cpfResponsavel;
    private javax.swing.JLabel crmMedico;
    private javax.swing.JLabel dataNascimento;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginFunc;
    private javax.swing.JLabel loginMedico;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nomeFunc;
    private javax.swing.JLabel nomeMedico;
    private javax.swing.JLabel nomePaciente;
    private javax.swing.JLabel nomeResponsavel;
    private javax.swing.JLabel numeroTelefone;
    private javax.swing.JPanel panelFuncionario;
    private javax.swing.JPanel panelMedico;
    private javax.swing.JPanel panelPaciente;
    // End of variables declaration//GEN-END:variables
}
