/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario.operacao;

import fachada.ServidorClinica;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import negocio.entidade.Funcionario;
import negocio.entidade.Medico;
import negocio.entidade.Paciente;
import negocio.excecao.funcionario.FuncionarioInexistenteException;
import negocio.excecao.medico.MedicoInexistenteException;
import negocio.excecao.paciente.PacienteInexistenteException;

/**
 *
 * @author Usuário
 */
public class JanelaBuscar extends javax.swing.JDialog {
    
    ServidorClinica fachada;
    
    /**
     * Creates new form JanelaBuscarPaciente
     */
    public JanelaBuscar(ServidorClinica fachada) {
        this.fachada = fachada;
        setResizable(false);
        setModal(true);
        initComponents();
        groupButton();
        campoCPF.setEnabled(false);
        campoCRM.setEnabled(false);
        campoId.setEnabled(false);
    }

    private void groupButton( ) {
        ButtonGroup bg1 = new ButtonGroup( );
        bg1.add(jRadioButtonPaciente);
        bg1.add(jRadioButtonMedico);
        bg1.add(jRadioButtonFuncionario);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonPaciente = new javax.swing.JRadioButton();
        jRadioButtonMedico = new javax.swing.JRadioButton();
        jRadioButtonFuncionario = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        BuscarMédico = new javax.swing.JPanel();
        campoCRM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        listaMedicos = new javax.swing.JButton();
        BuscarFuncionário = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        listaFuncionarios = new javax.swing.JButton();
        BuscarPaciente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoCPF = new javax.swing.JTextField();
        listaPacientes = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        botaoBuscar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Pessoas");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Buscar por:");

        jRadioButtonPaciente.setText("Paciente");
        jRadioButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPacienteActionPerformed(evt);
            }
        });

        jRadioButtonMedico.setText("Médico");
        jRadioButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedicoActionPerformed(evt);
            }
        });

        jRadioButtonFuncionario.setText("Funcionário");
        jRadioButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPaciente)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMedico)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonPaciente)
                    .addComponent(jRadioButtonMedico)
                    .addComponent(jRadioButtonFuncionario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainPanel.setLayout(new java.awt.CardLayout());

        campoCRM.setEditable(false);
        campoCRM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoCRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCRMActionPerformed(evt);
            }
        });
        campoCRM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCRMFocusGained(evt);
            }
        });
        campoCRM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCRMKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoCRMKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("CRM:");

        listaMedicos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaMedicos.setText("Exibir todos");
        listaMedicos.setToolTipText("Exibi uma lista com todos os medicos cadastrados.");
        listaMedicos.setEnabled(false);
        listaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMedicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscarMédicoLayout = new javax.swing.GroupLayout(BuscarMédico);
        BuscarMédico.setLayout(BuscarMédicoLayout);
        BuscarMédicoLayout.setHorizontalGroup(
            BuscarMédicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarMédicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaMedicos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BuscarMédicoLayout.setVerticalGroup(
            BuscarMédicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarMédicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscarMédicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaMedicos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(BuscarMédico, "buscarMedico");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("ID:");

        campoId.setEditable(false);
        campoId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdActionPerformed(evt);
            }
        });
        campoId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIdKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoIdKeyPressed(evt);
            }
        });

        listaFuncionarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaFuncionarios.setText("Exibir todos");
        listaFuncionarios.setToolTipText("Exibi uma lista com todos os medicos cadastrados.");
        listaFuncionarios.setEnabled(false);
        listaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaFuncionariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscarFuncionárioLayout = new javax.swing.GroupLayout(BuscarFuncionário);
        BuscarFuncionário.setLayout(BuscarFuncionárioLayout);
        BuscarFuncionárioLayout.setHorizontalGroup(
            BuscarFuncionárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarFuncionárioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaFuncionarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BuscarFuncionárioLayout.setVerticalGroup(
            BuscarFuncionárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarFuncionárioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscarFuncionárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaFuncionarios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(BuscarFuncionário, "buscarFuncionario");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CPF:");

        campoCPF.setEditable(false);
        campoCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCPFActionPerformed(evt);
            }
        });
        campoCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCPFKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoCPFKeyPressed(evt);
            }
        });

        listaPacientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaPacientes.setText("Exibir todos");
        listaPacientes.setToolTipText("Exibi uma lista com todos os medicos cadastrados.");
        listaPacientes.setEnabled(false);
        listaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPacientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscarPacienteLayout = new javax.swing.GroupLayout(BuscarPaciente);
        BuscarPaciente.setLayout(BuscarPacienteLayout);
        BuscarPacienteLayout.setHorizontalGroup(
            BuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaPacientes)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        BuscarPacienteLayout.setVerticalGroup(
            BuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaPacientes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(BuscarPaciente, "buscarPaciente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        botaoBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCancelar)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBuscar)
                    .addComponent(botaoCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCPFActionPerformed

    private void campoCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCPFKeyTyped
        int k = evt.getKeyChar();
        if((k > 47 && k < 58)) {
            if(campoCPF.getText().length() == 14){
                evt.setKeyChar((char)KeyEvent.VK_CLEAR);
                botaoBuscar.requestFocus();
            }else if(campoCPF.getText().length() == 11){
                campoCPF.setText(campoCPF.getText()+"-");
            }else if(campoCPF.getText().length() == 7){
                campoCPF.setText(campoCPF.getText()+".");
            }else if(campoCPF.getText().length() == 3){
                campoCPF.setText(campoCPF.getText()+".");
            }            
        } else {
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_campoCPFKeyTyped

    private void campoCRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCRMActionPerformed

    private void campoCRMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCRMKeyTyped
        int k = evt.getKeyChar();
        if((k <= 47 || k >= 58) || campoCRM.getText().length() > 8) {
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_campoCRMKeyTyped

    private void campoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdActionPerformed

    private void campoIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdKeyTyped
        int k = evt.getKeyChar();
        if((k <= 47 || k >= 58) || campoId.getText().length() > 8) {
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_campoIdKeyTyped

    private void jRadioButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPacienteActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "buscarPaciente");
        listaPacientes.setEnabled(true);
        campoCPF.setEnabled(true);
        campoCPF.setEditable(true);
    }//GEN-LAST:event_jRadioButtonPacienteActionPerformed

    private void jRadioButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedicoActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "buscarMedico");
        listaMedicos.setEnabled(true);
        campoCRM.setEnabled(true);
        campoCRM.setEditable(true);
    }//GEN-LAST:event_jRadioButtonMedicoActionPerformed

    private void jRadioButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFuncionarioActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "buscarFuncionario");
        listaFuncionarios.setEnabled(true);
        campoId.setEnabled(true);
        campoId.setEditable(true);
    }//GEN-LAST:event_jRadioButtonFuncionarioActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        if(jRadioButtonFuncionario.isSelected()){
            if(campoId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID inválido!","Erro",ERROR_MESSAGE);
            }else
                try {
                    Funcionario resultado = fachada.buscaFuncionario(campoId.getText());
                    new JanelaExibeObjeto(resultado, fachada).setVisible(true);
                } catch (FuncionarioInexistenteException ex) {
                    JOptionPane.showMessageDialog(null,ex.getMessage(),"Não encontrado!",INFORMATION_MESSAGE);
                }
        }else if(jRadioButtonMedico.isSelected()){
            if(campoCRM.getText().isEmpty() || campoCRM.getText().length() != 9){
                JOptionPane.showMessageDialog(null,"CRM inválido!","Erro",ERROR_MESSAGE);
            }else
                try {
                    Medico resultado = fachada.buscaMedico(campoCRM.getText());
                    new JanelaExibeObjeto(resultado, fachada).setVisible(true);
                } catch (MedicoInexistenteException ex) {
                    JOptionPane.showMessageDialog(null,ex.getMessage(),"Não encontrado!",INFORMATION_MESSAGE);
                }
        }else if(jRadioButtonPaciente.isSelected()){
            if(campoCPF.getText().isEmpty() || campoCPF.getText().length() != 14){
                JOptionPane.showMessageDialog(null,"CPF inválido!","Erro",ERROR_MESSAGE);
            }else
                try {
                    Paciente resultado = fachada.buscaPaciente(campoCPF.getText());
                    new JanelaExibeObjeto(resultado, fachada).setVisible(true);
                } catch (PacienteInexistenteException ex) {                
                    JOptionPane.showMessageDialog(null,ex.getMessage(),"Não encontrado!",INFORMATION_MESSAGE);
                }
        }else{
            JOptionPane.showMessageDialog(null,"Nada a pesquisar!","Erro",ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void campoCRMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCRMFocusGained
        
    }//GEN-LAST:event_campoCRMFocusGained

    private void campoCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCPFKeyPressed
        
    }//GEN-LAST:event_campoCPFKeyPressed

    private void campoIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdKeyPressed
        
    }//GEN-LAST:event_campoIdKeyPressed

    private void campoCRMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCRMKeyPressed
        
    }//GEN-LAST:event_campoCRMKeyPressed

    private void listaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMedicosActionPerformed
        new JanelaExibeLista(fachada.getMedicos().toString()).setVisible(true);
    }//GEN-LAST:event_listaMedicosActionPerformed

    private void listaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaFuncionariosActionPerformed
        new JanelaExibeLista(fachada.getFuncionarios().toString()).setVisible(true);
    }//GEN-LAST:event_listaFuncionariosActionPerformed

    private void listaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPacientesActionPerformed
        new JanelaExibeLista(fachada.getPaciente().toString()).setVisible(true);
    }//GEN-LAST:event_listaPacientesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuscarFuncionário;
    private javax.swing.JPanel BuscarMédico;
    private javax.swing.JPanel BuscarPaciente;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCRM;
    private javax.swing.JTextField campoId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButtonFuncionario;
    private javax.swing.JRadioButton jRadioButtonMedico;
    private javax.swing.JRadioButton jRadioButtonPaciente;
    private javax.swing.JButton listaFuncionarios;
    private javax.swing.JButton listaMedicos;
    private javax.swing.JButton listaPacientes;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
