/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario.operacao;

import fachada.ServidorClinica;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import negocio.entidade.Paciente;
import negocio.excecao.consulta.ConsultaInexistenteException;
import negocio.excecao.paciente.PacienteInexistenteException;

/**
 *
 * @author Usuário
 */
public class JanelaEmissaoLaudo extends javax.swing.JDialog {

    private ServidorClinica fachada;
    
    /**
     * Creates new form JanelaCadPaciente
     * @param fachada
     */
    
    public JanelaEmissaoLaudo(ServidorClinica fachada) {
        this.fachada = fachada;
        setModal(true);
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        botaoCancelar2 = new javax.swing.JButton();
        botaoEmitir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoParecer = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoAltura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoPeso = new javax.swing.JTextField();
        Informações = new javax.swing.JLabel();
        NomePaciente = new javax.swing.JLabel();
        campoCPF = new javax.swing.JTextField();
        campoCod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botaoCancelar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCancelar2.setText("Cancelar");
        botaoCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelar2ActionPerformed(evt);
            }
        });

        botaoEmitir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoEmitir.setText("Emitir");
        botaoEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEmitirActionPerformed(evt);
            }
        });

        campoParecer.setColumns(20);
        campoParecer.setRows(5);
        jScrollPane2.setViewportView(campoParecer);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Parecer médico:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("CPF do responsável:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Altura:");

        campoAltura.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAlturaActionPerformed(evt);
            }
        });
        campoAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoAlturaKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Peso:");

        campoPeso.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesoActionPerformed(evt);
            }
        });
        campoPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPesoKeyTyped(evt);
            }
        });

        Informações.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Informações.setText("Emissão de parecer médico");

        NomePaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NomePaciente.setText("-----------------------------------------------------------------");

        campoCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCPFActionPerformed(evt);
            }
        });
        campoCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCPFFocusLost(evt);
            }
        });
        campoCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCPFKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCPFKeyReleased(evt);
            }
        });

        campoCod.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodActionPerformed(evt);
            }
        });
        campoCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCodKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cód. da consulta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCod, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(botaoEmitir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoCancelar2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCPF))
                            .addComponent(NomePaciente)
                            .addComponent(Informações))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Informações)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomePaciente)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(campoCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoEmitir)
                        .addComponent(botaoCancelar2)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelar2ActionPerformed
        int resul = JOptionPane.showConfirmDialog(null, "Deseja cancelar?","Confirmação",JOptionPane.YES_OPTION);
        if(resul == 0) dispose();
    }//GEN-LAST:event_botaoCancelar2ActionPerformed

    private void botaoEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEmitirActionPerformed
        if(campoCPF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Por favor, informe o CPF!","Atenção",ERROR_MESSAGE);
        }else if(campoParecer.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Laudo não pode ser emitido sem o parecer!","Atenção",ERROR_MESSAGE);
        }else if(campoCod.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Por favor, digite o código da consulta!","Atenção",ERROR_MESSAGE);
        }else{
            try {
                fachada.emitirLaudo(campoCod.getText(),  Double.parseDouble(campoAltura.getText()),  Double.parseDouble(campoPeso.getText()), campoParecer.getText());
                dispose();
            } catch (ConsultaInexistenteException ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage(),"Atenção",ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botaoEmitirActionPerformed

    private void campoAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAlturaActionPerformed

    private void campoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesoActionPerformed

    private void campoCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCPFKeyReleased
        // TODO add your handling code here:
        if (campoCPF.getText().length() != 13)
        NomePaciente.setText("-----------------------------------------------------------------");
    }//GEN-LAST:event_campoCPFKeyReleased

    private void campoCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCPFKeyTyped
        int k = evt.getKeyChar();
        if((k > 47 && k < 58)) {
            if(campoCPF.getText().length() == 14){
                evt.setKeyChar((char)KeyEvent.VK_CLEAR);
            }else if(campoCPF.getText().length() == 11){
                campoCPF.setText(campoCPF.getText()+"-");
            }else if(campoCPF.getText().length() == 7){
                campoCPF.setText(campoCPF.getText()+".");
            }else if(campoCPF.getText().length() == 3){
                campoCPF.setText(campoCPF.getText()+".");
            }
        } else {
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_campoCPFKeyTyped

    private void campoCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFFocusLost
        if (campoCPF.getText().isEmpty())
            NomePaciente.setText("-- CPF não pode ser vazio --");
        else if(campoCPF.getText().length() < 13)
            NomePaciente.setText("CPF inválido");
        else
            try {
                Paciente p = fachada.buscaPaciente(campoCPF.getText());
                NomePaciente.setText(p.getNome());
            } catch (PacienteInexistenteException ex) {
                NomePaciente.setText(ex.getMessage());
                campoCPF.setText(" ");
                campoCPF.requestFocus();
            }
    }//GEN-LAST:event_campoCPFFocusLost

    private void campoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCPFActionPerformed

    private void campoCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodActionPerformed

    private void campoAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAlturaKeyTyped
        int k = evt.getKeyChar();
        if((k <= 47 || k >= 58)) 
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
    }//GEN-LAST:event_campoAlturaKeyTyped

    private void campoPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesoKeyTyped
        int k = evt.getKeyChar();
        if((k <= 47 || k >= 58)) 
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
    }//GEN-LAST:event_campoPesoKeyTyped

    private void campoCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCodKeyTyped
        int k = evt.getKeyChar();
        if((k <= 47 || k >= 58)) 
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
    }//GEN-LAST:event_campoCodKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Informações;
    private javax.swing.JLabel NomePaciente;
    private javax.swing.JButton botaoCancelar2;
    private javax.swing.JButton botaoEmitir;
    private javax.swing.JTextField campoAltura;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCod;
    private javax.swing.JTextArea campoParecer;
    private javax.swing.JTextField campoPeso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
